
services:
  backend:
    build: .
    container_name: student-portal-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
      - /app/node_modules



      